auctions/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'auctions'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("like_view/<int:listing_id>",views.like_view, name = "like" ),
    path("unlike_view/<int:listing_id>",views.unlike_view, name = "unlike" ),
    path("page_view/<int:listing_id>", views.page_view, name = "page" ),
    path("addlisting",views.addListing_view, name="addlisting"),
    path("addcomment_view/<int:listing_id>", views.addComment_view, name= "comment"),
    path("watchlist",views.watchlist, name = "watchlist"),
    path("profile", views.profileView,name= "profile"),
    path("deleteListing/<int:listingID>",views.deleteListing_view, name="deleteListing"),
    path("placeBidView/<int:listingID>", views.placeBidView, name= "placeBid"),
    path("buy/<int:listingID>", views.buy, name = "buy"),
    path("deleteComment_view/<int:listingID>/<int:commentID>", views.deleteComment_view, name= "dcomment")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                                document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from gettext import Catalog
from pickle import TRUE
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.files.storage import FileSystemStorage
import datetime
from django.utils import timezone

class User(AbstractUser):
    first  = models.CharField(max_length=50)
    last   = models.CharField(max_length=65)
    username = models.CharField(max_length=65, unique=True)
    email = models.EmailField( max_length=254)
    
    def __str__(self)->str:
        return f"{self.first} {self.last}"
class Listing(models.Model):
    itemName  = models.CharField(max_length=65)
    likes = models.IntegerField(default=0)
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    catagory  = models.CharField(max_length=50)
    price =  models.FloatField()
    description = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to = 'auctions/images')
    def __str__(self)-> str:
        return f"Item Name:{self.itemName}, Created By:{self.poster}, Price: {self.price}"
class Bid(models.Model):
    listing = models.ForeignKey(Listing,on_delete = models.CASCADE)
    placedBy  = models.ForeignKey(User,on_delete=models.CASCADE)
    bidPrice =  models.IntegerField()
    def __str__(self) -> str:
        return f"{self.placedBy} bid {self.bidPrice} for {self.listing}"
class Comment(models.Model):
    post = models.ForeignKey(Listing, on_delete=models.CASCADE)
    placeby = models.ForeignKey(User,on_delete=models.CASCADE)   
    comment = models.TextField()
    time = models.DateTimeField(default=timezone.now)
    def __str__(self)->str:
        return f"{self.placeby} commeneted{self.comment} on {self.post}"
class Like(models.Model):
    post = models.ForeignKey(Listing, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    liked = models.BooleanField(default=False)
    def __str__(self)->str:
        return f"{self.user} liked {self.post}"

class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title

1

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

import auctions
from .models import Like, User, Bid, Listing, Comment

cats = ["Hoodies", "Shirts", "Pants", "Hats", "Electronics", "Skateboards","Accessories", "Shoes"]
def index(request):
    images = map(lambda x: x.image, Listing.objects.all())
    cats = ["Hoodies", "Shirts", "Pants", "Hats", "Electronics", "Skateboards","Accessories", "Shoes"]
    try : 
        like_list = list(map(lambda x : x.post.id, Like.objects.filter(user = request.user)))
    except:
        like_list = []
    if request.method == "GET" and "cat" in request.GET:
        cat = request.GET["cat"]
        if cat == "All":
            return render(request, "auctions/index.html", {"listings": Listing.objects.all(), "images":images, "userlikes":like_list, "cats" :cats})
        return render(request, "auctions/index.html", {"listings": Listing.objects.filter(catagory = cat), "images":images, "userlikes":like_list, "cats" :cats})
    return render(request, "auctions/index.html", {"listings": Listing.objects.all(), "images":images, "userlikes":like_list, "cats" :cats}
    )


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in

        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username = username, email = email, password =password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")
@login_required
def like_view(request, listing_id):
    if request.method == "POST":
        listing_finder = Listing.objects.get(pk=listing_id)
        try : 
            like_exist = Like.objects.get(user = request.user, post = listing_finder)
        except:
            like_exist = None
        if like_exist is None:
            newlike = Like(post=listing_finder, user = request.user, liked = True)
            newlike.save()
            listing_finder.likes +=1
            listing_finder.save()
            return HttpResponseRedirect(reverse("auctions:index"))
    return HttpResponseRedirect(reverse("auctions:index"))
@login_required
def unlike_view(request, listing_id):
    if request.method == "POST":
        listing_finder = Listing.objects.get(pk=listing_id)
        try : 
            like_exist = Like.objects.get(user = request.user, post = Listing.objects.get(pk=listing_id))
        except:
            like_exist = None
        if like_exist is not None:
            listing_finder = Listing.objects.get(pk=listing_id)
            listing_finder.likes -=1
            listing_finder.save()
            like_exist.delete()
            return HttpResponseRedirect(reverse("auctions:index"))
    return HttpResponseRedirect(reverse("auctions:index"))
def page_view(request,listing_id):
    listing = Listing.objects.get(pk =listing_id)
    try:
        highestbid = max(list(map(lambda x : x.bidPrice ,Bid.objects.filter(listing = listing))))
    except:
        highestbid = "No currentbids"   
    try: 
        comments = Comment.objects.filter(post=listing)
    except :
        comments = "No comments"        
    return render(request, "auctions/page.html", {"listing":listing, "highestbid":highestbid, "comments":comments})


def addListing_view(request):
    if request.method  == "POST":
        new_ = Listing(itemName = request.POST["itemName"], catagory = request.POST["Catagory"], price = request.POST["cost"], image = request.FILES["image"], description = request.POST["description"], poster = User.objects.get(pk=request.user.id))
        new_.save()
        return render(request, "auctions/addlisting.html",{"cats": cats})
    return render(request, "auctions/addlisting.html", {"cats": cats})
def deleteListing_view(request, listingID):
    if Listing.objects.get(pk=listingID):
        Listing.objects.get(pk=listingID).delete()
    return HttpResponseRedirect(reverse("auctions:profile"))
def addComment_view(request,listing_id):
    if request.user.is_authenticated:
        if request.method == "POST":
            currentuser = request.user
            listing  =  Listing.objects.get(pk = listing_id )
            comment = request.POST["comment"]
            Comment(post = listing ,placeby = currentuser, comment = comment).save()
            return HttpResponseRedirect(reverse("auctions:page", kwargs={'listing_id':listing_id}))
    return HttpResponseRedirect(reverse("auctions:login"))
def watchlist(request):
    liked = Like.objects.filter(user = request.user)
    likedlistings = list(map(lambda x : x.post, liked))
    return render(request, "auctions/watchlist.html" , {"likedlistings":likedlistings})
def profileView(request):
    listings = Listing.objects.filter(poster= request.user)
    return render(request,"auctions/profile.html", {"listings":listings})

def placeBidView(request, listingID):
    if request.user.is_authenticated:
        bidValue = request.POST["bid"]
        if Listing.objects.get(pk=listingID):
                listing = Listing.objects.get(pk=listingID)
                placedBy  = User.objects.get(pk=request.user.id)
                Bid(listing = listing, placedBy=placedBy, bidPrice=bidValue).save()
        return HttpResponseRedirect(reverse("auctions:page", kwargs={'listing_id':listingID }))
    return HttpResponseRedirect(request, "auctions/index.html")
    
def buy(request,listingID):
    return render(request, "auctions/buy.html")

def deleteComment_view(request,listingID,commentID):
    
    Comment.objects.get(pk = commentID).delete()
    return HttpResponseRedirect(reverse("auctions:page", kwargs={'listing_id':listingID}))

auctions/templates/auctions/addlisting.html
{% extends 'auctions/layout.html' %}
{% block title %}Add Listing{% endblock title %}
{% block body %}

<div class = "container">
    <h1> Add Listing</h1>
    <form  action = "{% url 'auctions:addlisting' %}" method = "POST" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label> Item Name</label>
            <input type="text" class="form-control" name = "itemName" placeholder="Enter Item Name" required>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Catagory</label>
            <select name  = "Catagory" class="form-control">
              {% for cat in cats %}
              <option>{{cat}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group col-md-2">
            <label>Buying Price</label>
            <input type="number" class="form-control" name = "cost"  min = "0" required>
          </div>
        </div>
        <div class="form-row" >
            <div class="form-group col-md-4">
            <label>Upload Image</label>
                <input type = "file" name = "image" required>
            </div>
        </div>
        <div class="form-row" >
            <label>Descrpition</label>
            <textarea  style = "resize: none"type="text" class="form-control" name = "description" placeholder="" rows="4" cols="50" required> </textarea>
          </div>
        <div class="from-row" >
        <input type = "submit" class = "btn btn-danger" required>
        </div>
      </form>
    </div>
</div>
</div>
{% endblock body %}

auctions/templates/auctions/buy.html
{% extends 'auctions/layout.html' %}
{% block body %}
<h1> Can't buy anything right now.<h1>
{% endblock body %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block body %}
    <div class = "container">
        <div class = "row">
            <div class = "col-12">
                <h2>Active Listings</h2>
            </div>
        <div class = "col">
            <form action = "{%url 'auctions:index'%}" method == "GET" name = "cat">
                    <select class = "form-select" name ="cat">
                    <option type="submit" name = "cat">All</option>
                    {% for cat in cats %}
                    <option type="submit" name = "cat">{{cat}}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Search" class="myButton" name = "submit">
            </form>
        </div>
    </div>
</div>
    {%if listings%}
    <div class = "container-fluid align-items-lg-center" style="text-align:center">
    {% for listing in  listings %}
        {% if forloop.first %}<div class="row col-md-12">{% endif %}
        <div class="col-md-4">
            <div class = "hovereffect">
                <a href = "{%url 'auctions:page' listing.id%} ">
                <img class="img-responsive" width="300" src="{%static "/"%}{{listing.image}}" alt="{{listing.image}}">
            </div>
            <div>
                <div class="row justify-content-center">
                    <div class="col-3 " style = "text-align: center; padding: 6px 0;" >
                        <text style ="color:black ; display: inline-block;"> Likes: {{listing.likes}} </text>
                     </div>
                    <div class="col-3">
                        {% if user.is_authenticated %}
                            {%if listing.id in userlikes%}
                            <form action = "{%url 'auctions:unlike' listing.id%}" method = "POST">
                                {% csrf_token %}
                            <input type="submit" name = {{listing}} value = "Liked"  class="btn btn-dark" >
                            {% else %}
                            <form action = "{%url 'auctions:like' listing.id%}" method = "POST">
                                {% csrf_token %}
                            <input type="submit" name = {{listing}} value = "Like"  class="btn btn-dark">
                            {% endif %}
                        {% else %}
                            <form action = "{%url 'auctions:login'%}">
                            <input type="submit" name = {{listing}} value = "Like"  class="btn btn-dark">
                        {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
        </div>
    {% endif %}

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <header>
    <nav class = "navbar navbar-expand-sm bg-light">
        
            <div class = "row">
                <div class = "col-4">
                    <a routerLink="/" class="navbar-brand" href="#">Auctions</a>
                </div>
            </div>
        </div
        </div>
            <ul class="nav ml-auto" >
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watch List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:addlisting' %}">Add Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'auctions:profile'%}">{{request.user.username.capitalize}}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:login' %}">Add Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                    </li>
                {% endif %}
                    
            </ul>
        </nav>
     </nav>
    </header>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class = "container">
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group ">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
</div>

{% endblock %}

auctions/templates/auctions/page.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block title %}
{{listing.itemName}}
{% endblock title %}
{% block body %}
{%if listing%}
<div class = "container">
    <div class = "row">
        <div class = "col">
            <img width="500" src="{% static '/'%}{{listing.image}}" alt="{{listing.itemName}}">
        </div>
        <div class = "col justify-content-center">
            <h1>{{listing.itemName}}</h1>
            <ul class="list-group list-group-flush "> 
            <li class="list-group-item"> Catagory: {{listing.catagory}}</li>
            <li class="list-group-item"> Item Name: {{listing.itemName}}</li>
            <li class="list-group-item"> Price: ${{listing.price}}</li>
            <li class="list-group-item"> Posted by: {{listing.poster.username}}</li>
            <li class= "list-group-item"> Created on: {{listing.date}}</li>
            </ul>

            <div class="row">
                <div class="col justify-content-center">
                    <h2>Highest Bid:
                            {% if highestbid %}
                                {{highestbid}} 
                            {% else %} 
                            No Current Bids
                            {% endif %}
                    </h2>
                </div>
                <div class="col">
                    <label for="curreny">Bid</label>
                    {% if request.user.is_authenticated %}
                    <form action = "{% url 'auctions:placeBid' listing.id %}" method = 'POST'>
                        {% csrf_token %}
                        <input type="number" min="0" max = "{{listing.price}}" name = "bid" required>
                        <input type="Submit" class="btn-danger" value = "Place Bid">
                    </form>
                    {% else %}
                    <form action = "{% url 'auctions:login' %}">
                        {% csrf_token %}
                        <input type="number" min="0" max = "{{listing.price}}" name = "bid" required>
                        <input type="Submit" class="btn-danger" value = "Place Bid">
                    </form>
                    {% endif %}
                
                </div>
                 <div class="col">
                    <label for="curreny">Buy for asking price</label>
                    <form action = "{% url 'auctions:buy' listing.id %}" method = 'POST'>
                         {% csrf_token %}
                        <input type="Submit" class="btn-danger" value = "Buy">
                    </form>
                </div>
            </div>
        </div>
</div>
{% endif %}
<div class ="container-flex">
            <div class="form-group">
                <form   action = "{%url 'auctions:comment' listing.id%}" method = "POST">
                    {% csrf_token %}
                 <textarea  class="form-control" name = "comment" rows="3" cols="100" placeholder = "Commment"> </textarea>
                <input type="submit" value = "Submit">
                </form>
            </div>
{% comment %}  {% endcomment %}
    {% if comments %}
        {% for comment in comments%}
        <div class = "container">
            <div class = "row">
                <div class = "col">
                    <h3>{{comment.placeby.username}}</h3>
                </div>
                <div class = "col-2">
                    <p>{{comment.time}}</p>
  
                </div>
            </div>
            <div class = "row">
                <p>{{comment.comment}}</p>
            </div> 
            {% if request.user.username == comment.placeby.username %}
            <div class = "row">
                <form  action = "{%url 'auctions:dcomment' listingID=listing.id commentID=comment.id %}" method = "delete">
                    {% csrf_token %}
                <input type="submit" value = "Delete">
                </form>
            </div>
            {% endif %}
        </div>

            <hr/>

        {% endfor %}
    {% else %}
    <div class = "row">
        <div class  = "col">
        <p> No comments<p>
    </div>
    {% endif %}
{% endblock body %}

auctions/templates/auctions/profile.html
{% extends 'auctions/layout.html'%}
{% load static %}

{% block title %}{{request.user}}{% endblock title %}
{% block body %}
<h1> {{request.user}}</h1>
{% if listings%}
    
        
    {% for listing in listings %}
    <div class= "container"> 
        <div class = "row">
            <div class = "col">
                <img  width="300" src="{% static '/'%}{{listing.image}}" > 
            </div>
            <div class = "col-5">
                <ul class="list-group  "> 
                    <li class="list-group-item"> Catagory: {{listing.catagory}}</li>
                    <li class="list-group-item"> Item Name: {{listing.itemName}}</li>
                    <li class="list-group-item"> Price: ${{listing.price}}</li>
                    <li class="list-group-item"> Posted by: {{listing.poster.username}}</li>
                    <li class= "list-group-item"> Created on: {{listing.date}}</li>
                </ul>
            </div>
            <div class = "col-1">
                <form action = "{% url 'auctions:deleteListing' listing.id %}" method = "Delete">
                    {% csrf_token %}
                    <input type = "submit" class = "btn btn-danger" value="Delete"> 
                </form>   
            </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% else %}
        <h2> You've adding no listing </h2>
{% endif %}

{% endblock body %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

   
    
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class = "container">
        <h2>Register</h2>
        <form action="{% url 'auctions:register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Register">
        </form>

        Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
    </div>
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/index.html' %}
{% load static %}

{% block title %}Liked Items{% endblock title %}

{% block body %}
<div class = "d-flex justify-content-center">
<h1> Liked Items </h1>
</div>
<div class = "d-flex justify-content-center">
    {% if likedlistings %}
    <div class= "container"> 
    {% for listing in likedlistings %}
        <div class = "row">
            <div class = "col">
                <img  width="300" src="{% static '/'%}{{listing.image}}" > 
            </div>
            <div class = "col">
                <ul class="list-group  "> 
                    <li class="list-group-item"> Catagory: {{listing.catagory}}</li>
                    <li class="list-group-item"> Item Name: {{listing.itemName}}</li>
                    <li class="list-group-item"> Price: ${{listing.price}}</li>
                    <li class="list-group-item"> Posted by: {{listing.poster.username}}</li>
                    <li class= "list-group-item"> Created on: {{listing.date}}</li>
                </ul>
            </div>
        </div>
    {% endfor %}
    {% else %}
    <a href= "{% url 'auctions:index' %}"><h1> No Liked post</h1></a>
    {% endif %}

</div>

{% endblock body %}